# Generated by Django 6.0.5 on 2026-06-26 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_tasks_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='Task_Description',
            new_name='task_description',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='Task_Name',
            new_name='task_name',
        ),
    ]
